#!/usr/bin/python

from os import path , pardir , chdir , listdir , getcwd , mkdir , stat
from shutil import copy
from subprocess import Popen , PIPE

try:
    mkdir("TEST_NOTE")
except:
    print "To run remove TEST_NIOTE"
    exit(1)

testresults = open("testresults" , "w")

copy(path.join(path.dirname(__file__) , pardir , "note") , path.join(path.dirname(__file__) , "TEST_NOTE"))

chdir("TEST_NOTE")

# Start note

Popen(["./note"] , stdin = PIPE , stdout = PIPE).communicate(input=b"y\ny\ny\ny\n")

#
# TEST 1 - check if all files and directories are created on startup
#

ok = True

ls = listdir(getcwd())
normal = ['setup', 'TEMPLATE', '.selection', 'note', 'TRASH', 'NOTES']
for file in ls:
    if not file in normal:
        ok = False
if not len(ls) == len(normal):
    ok = False

try:
    stat(path.join(getcwd() , "TEMPLATE" , "template.tex"))
except:
    ok = False

testresults.write("".join([str(ok) , "\t - all directories and files created created\n"]))

#
# TEST 2 - create simple note
#

ok = True

Popen(["./note" , "-key" , "sosdsdme" , "kesdssssdy" , "-title" , "some_tisdsdtle" , "-create"]).wait()

out = Popen(["./note" , "-list"] , stdin = PIPE , stdout = PIPE).communicate()

if not "sosdsdme".upper() in out[0]:
    ok = False

if not "kesdssssdy".upper() in out[0]:
    ok = False

if not "some_tisdsdtle" in out[0]:
    ok = False

testresults.write("".join([str(ok) , "\t - note created with success\n"]))




